language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t luizparo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true luizparo/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-123777059602"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY