language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t luizparo/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true luizparo/docker-react npm run test